apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-serv
  namespace: default
spec:
  selector:
    matchLabels:
      app: grpc-serv
  replicas: 1
  template:
    metadata:
      name: grpc-serv
      labels:
        app: grpc-serv
    spec:
      containers:
        - name: grpc-serv
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_password
            - name: POSTGRES_HOST
              value: localhost
          image: ameleshko/grpc:grpc-serv
        - image: postgres
          name: postgres
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data