version: "3"

services:
  db:
    image: "postgres"
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - database.env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=demo

  adminer:
    image: adminer
    restart: always
    ports:
      - "6080:8080"

  srv:
    build: ./demo-grpc-server
    restart: always
    ports:
      - "9091:9091"
    networks:
      - app_net: product
#        ipv4_address: 111.111.111.111

    env_file:
      - database.env
#    environment:
#      - DOCKER_HOST=172.20.0.1



  client:
    build: ./demo-rest
    restart: always
    depends_on:
      - srv
    ports:
      - "8080:8080"
    networks:
      - app_net: product

    environment:
#      SERVER_HOST: srv
      SERVER_PORT: 8080
#      DEMO_GRPC_HOST: 172.20.0.1


networks:
  app_net:
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.28.0.0/16
    name: product


#networks:
#  app_net:
#    driver: host
#    ipam:
#      driver: default
#      config:
#        - subnet: 192.168.2.0/24