version: "3"

services:
  db:
    image: "postgres"
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - database.env

  adminer:
    image: adminer
    restart: always
    ports:
      - "6080:8080"

  srv:
    build: ./demo-grpc-server
    restart: always
    ports:
      - "8085:9091"
    environment:
      SPRING_DATABASE_SERVER: db
      SPRING_DATABASE_URL: jdbc:postgresql://db/demo
      SPRING_DATABASE_USERNAME: postgres
      SPRING_DATABASE_PASSWORD: postgres
      SPRING_DATABASE_SCHEMA: postgres
      SPRING_DATABASE_DB: demo
      SPRING_DATABASE_PORT: 5432

  client:
    build: ./demo-rest
    environment:
      SERVER_HOST: srv
      SERVER_PORT: 9091
      SPRING_DATABASE_SERVER: db
      SPRING_DATABASE_URL: jdbc:postgresql://db/demo
      SPRING_DATABASE_USERNAME: postgres
      SPRING_DATABASE_PASSWORD: postgres
      SPRING_DATABASE_SCHEMA: postgres
      SPRING_DATABASE_DB: demo
      SPRING_DATABASE_PORT: 5432
    restart: always
    depends_on:
      - srv
    ports:
      - "8084:8082"